name: 'Block Blob Split Upload'
description: 'Upload files as a block blob to Azure Storage Account. Split the blob in blocks based on a predefined separator'
inputs:
  separator:
    description: 'String that will be used as a separator on the text file.'
    required: true
    default: '<comments/>'
  fileFilter:
    description: 'Comma separated file extensions that should be split before uploading'
    required: true
    default: 'htm,html'
outputs:
runs:
  using: 'node20'
  main: 'index.js'
